# **2303A52249 - B43**
# **A.VAMSHI KRISHNA**
**ASSIGNMENT-2.4**


# **TASK-1**
Book Class Generation

❖ Scenario:
You are building a simple library management module.

❖ Task:
Use Cursor AI to generate a Python class Book with attributes title, author,
and a summary() method.

❖ Expected Output:

➢ Generated class

➢ Student commentary on code quality

In [1]:
class Book:
    def __init__(self, title, author):
        self.title = title
        self.author = author

    def summary(self):
        return f"{self.title} by {self.author}"

## **EXPLANATION AND OBSERVATION**

### Student Commentary on Code Quality

**Clarity and Readability:**
The `Book` class is very clear and easy to understand. The attribute names `title` and `author` are descriptive, and the `summary()` method's purpose is immediately obvious.

**Simplicity:**
The code is concise and does exactly what is asked without unnecessary complexity. The `__init__` method correctly initializes the attributes, and the `summary` method provides a straightforward string representation.

**Completeness:**
For the given task, the class is complete. It includes the required attributes and the `summary()` method.

**Potential Enhancements (for a more robust system):**
*   **Input Validation:** For a real-world application, you might want to add validation in the `__init__` method to ensure `title` and `author` are non-empty strings.
*   **Docstrings:** Adding docstrings to the class and its methods would improve documentation, especially for larger projects or if others need to use this code.
*   **`__repr__` Method:** Implementing a `__repr__` method would provide a more developer-friendly string representation of the object, useful for debugging.
*   **Error Handling:** Depending on future requirements, more robust error handling might be needed.

Overall, for the defined task, the code quality is excellent in terms of clarity, simplicity, and direct fulfillment of requirements.

# **TASK-2**
Sorting Dictionaries with AI

❖ Scenario:
You need to sort user records by age.

❖ Task:
Use Gemini and Cursor AI to generate code that sorts a list of dictionaries
by a key.

❖ Expected Output:

➢ Both AI outputs

➢ Comparison of clarity and performance

In [2]:
# Sample list of dictionaries
users = [
    {'name': 'Alice', 'age': 30},
    {'name': 'Bob', 'age': 24},
    {'name': 'Charlie', 'age': 35},
    {'name': 'David', 'age': 24}
]

# Sort the list of dictionaries by 'age'
sorted_users = sorted(users, key=lambda user: user['age'])

print("Sorted by age:")
for user in sorted_users:
    print(user)

# Sort the list of dictionaries by 'age' in descending order
sorted_users_desc = sorted(users, key=lambda user: user['age'], reverse=True)

print("\nSorted by age (descending):")
for user in sorted_users_desc:
    print(user)

# Sort by 'age' and then by 'name' for stable sorting
sorted_users_multi = sorted(users, key=lambda user: (user['age'], user['name']))

print("\nSorted by age, then name:")
for user in sorted_users_multi:
    print(user)

Sorted by age:
{'name': 'Bob', 'age': 24}
{'name': 'David', 'age': 24}
{'name': 'Alice', 'age': 30}
{'name': 'Charlie', 'age': 35}

Sorted by age (descending):
{'name': 'Charlie', 'age': 35}
{'name': 'Alice', 'age': 30}
{'name': 'Bob', 'age': 24}
{'name': 'David', 'age': 24}

Sorted by age, then name:
{'name': 'Bob', 'age': 24}
{'name': 'David', 'age': 24}
{'name': 'Alice', 'age': 30}
{'name': 'Charlie', 'age': 35}


## **COMPARISION**

### Comparison of Clarity and Performance

**Clarity:**
The generated code uses Python's built-in `sorted()` function with a `lambda` function as the `key` argument. This approach is highly Pythonic and generally considered very clear and readable, especially for those familiar with functional programming concepts in Python.

*   `sorted(iterable, key=lambda item: item['key_name'])`: This pattern is a standard and widely understood way to sort complex data structures in Python. The `lambda` function concisely specifies the sorting criterion.
*   Adding `reverse=True` clearly indicates descending order.
*   Sorting by multiple keys (e.g., `(user['age'], user['name'])`) is also straightforward and readable, as Python's `sorted()` function handles tuples for multi-level sorting naturally.

**Performance:**

The `sorted()` function in Python, which is based on Timsort, offers excellent performance characteristics:

*   **Time Complexity:** The average and worst-case time complexity for `sorted()` is O(n log n), where 'n' is the number of elements in the list. This is an efficient sorting algorithm.
*   **Space Complexity:** The `sorted()` function creates a new sorted list, so its space complexity is O(n).
*   **Stability:** Timsort is a stable sorting algorithm, which means that if two elements have the same key, their relative order in the original list is preserved in the sorted list. This is particularly useful when sorting by multiple keys (as demonstrated in the 'Sorted by age, then name' example, where users with the same age maintain their original order based on their name implicitly unless explicitly sorted by name).

For typical data sizes encountered in most applications, this method provides a highly efficient and clear solution for sorting lists of dictionaries.

# **TASK-3**
Calculator Using Functions

❖ Scenario:
You are reviewing a basic calculator module.

❖ Task:
Ask Gemini to generate a calculator using functions and explain how it
works.

In [6]:
def add(x, y):
    """Adds two numbers."""
    return x + y

def subtract(x, y):
    """Subtracts two numbers."""
    return x - y

def multiply(x, y):
    """Multiplies two numbers."""
    return x * y

def divide(x, y):
    """Divides two numbers. Handles division by zero."""
    if y == 0:
        return "Error: Cannot divide by zero!"
    return x / y

def calculator():
    """A simple console-based calculator that performs basic arithmetic operations."""
    print("Simple Calculator")
    print("Select operation:")
    print("1. Add")
    print("2. Subtract")
    print("3. Multiply")
    print("4. Divide")

    while True:
        choice = input("Enter choice (1/2/3/4): ")

        if choice in ('1', '2', '3', '4'):
            try:
                num1 = float(input("Enter first number: "))
                num2 = float(input("Enter second number: "))
            except ValueError:
                print("Invalid input. Please enter numbers only.")
                continue

            if choice == '1':
                print(f"{num1} + {num2} = {add(num1, num2)}")
            elif choice == '2':
                print(f"{num1} - {num2} = {subtract(num1, num2)}")
            elif choice == '3':
                print(f"{num1} * {num2} = {multiply(num1, num2)}")
            elif choice == '4':
                print(f"{num1} / {num2} = {divide(num1, num2)}")

            next_calculation = input("Let's do next calculation? (yes/no): ")
            if next_calculation.lower() == "no":
                break
        else:
            print("Invalid input. Please enter a valid choice (1/2/3/4).")

# To run the calculator, uncomment the line below:
# calculator()


### AI Explanation of the Calculator Code

This Python code defines a simple command-line calculator using separate functions for each arithmetic operation, which enhances modularity and readability.

**Functions:**::

*   `add(x, y)`: Takes two numbers, `x` and `y`, and returns their sum.
*   `subtract(x, y)`: Takes two numbers, `x` and `y`, and returns their difference.
*   `multiply(x, y)`: Takes two numbers, `x` and `y`, and returns their product.
*   `divide(x, y)`: Takes two numbers, `x` and `y`, and returns their quotient. It includes basic error handling to prevent division by zero.

**`calculator()` Function:**

This is the main function that orchestrates the calculator's operation:

1.  **Menu Display:** It first prints a menu of available operations (Add, Subtract, Multiply, Divide).
2.  **Input Loop:** It enters an infinite loop (`while True`) to allow multiple calculations until the user decides to exit.
3.  **Choice Selection:** It prompts the user to enter their choice of operation (1, 2, 3, or 4).
4.  **Input Validation:**
    *   It checks if the `choice` is one of the valid options.
    *   It attempts to convert the user's input for two numbers (`num1`, `num2`) into floating-point numbers. If this conversion fails (e.g., the user enters text instead of numbers), it catches a `ValueError` and prompts the user for valid input.
5.  **Operation Execution:** Based on the user's `choice`, it calls the appropriate arithmetic function (`add`, `subtract`, `multiply`, `divide`) with `num1` and `num2` as arguments and prints the result.
6.  **Continue or Exit:** After each calculation, it asks the user if they want to perform another calculation. If the user enters "no" (case-insensitive), the loop breaks, and the calculator exits.
7.  **Invalid Choice Handling:** If the user enters an invalid choice (not 1, 2, 3, or 4), it prints an error message.

**How to Use:**

To use the calculator, uncomment the line `calculator()` at the end of the code and then run the cell. The program will then prompt you for input in the output console.

Please provide a screenshot of the calculator in action after running the `calculator()` function.

## **Task- 4**

Generate a Python program to check for Armstrong numbers.
Armstrong Number Optimization

❖ Scenario:
An existing solution is inefficient.

❖ Task:
Generate an Armstrong number program using Gemini, then improve it
using Cursor AI.

## Generate Initial Armstrong Number Program

### Subtask:
Generate a Python program to check for Armstrong numbers.


**Reasoning**:
The subtask requires generating a Python function to check for Armstrong numbers and demonstrating its usage. I will create a code block that implements the `is_armstrong` function according to the instructions and includes an example.



In [4]:
def is_armstrong(number):

    # Convert the number to a string to easily count digits and iterate
    num_str = str(number)
    num_digits = len(num_str)

    sum_of_powers = 0
    for digit_char in num_str:
        digit = int(digit_char)
        sum_of_powers += digit ** num_digits

    return sum_of_powers == number

# Example usage:
print(f"Is 153 an Armstrong number? {is_armstrong(153)}")  # Expected: True
print(f"Is 9 an Armstrong number? {is_armstrong(9)}")    # Expected: True
print(f"Is 371 an Armstrong number? {is_armstrong(371)}")  # Expected: True
print(f"Is 123 an Armstrong number? {is_armstrong(123)}")  # Expected: False
print(f"Is 1634 an Armstrong number? {is_armstrong(1634)}") # Expected: True

Is 153 an Armstrong number? True
Is 9 an Armstrong number? True
Is 371 an Armstrong number? True
Is 123 an Armstrong number? False
Is 1634 an Armstrong number? True


## Explain Initial Program

### Subtask:
Provide an explanation of the generated Armstrong number program, detailing its logic and how it identifies Armstrong numbers.


### Explanation of the `is_armstrong` function

The `is_armstrong` function is designed to check if a given integer is an Armstrong number. An Armstrong number is a special type of number where the sum of its own digits, each raised to the power of the total number of digits, equals the original number itself. For example, 153 is an Armstrong number because it has 3 digits, and 1^3 + 5^3 + 3^3 = 1 + 125 + 27 = 153.

Here's a breakdown of the function's logic:

1.  **Convert to String and Count Digits:**
    The first step inside the function is to convert the input `number` into a string (`num_str`). This conversion is crucial because it allows us to easily determine two key pieces of information:
    *   The total number of digits in the number (`num_digits`) by taking the length of the string (`len(num_str)`).
    *   Individual digits can be easily accessed by iterating through the characters of the string.

2.  **Calculate Sum of Powers:**
    A variable `sum_of_powers` is initialized to `0`. The code then enters a `for` loop that iterates through each character (`digit_char`) in the `num_str`.
    *   Inside the loop, each `digit_char` (which is a string) is converted back into an integer (`digit = int(digit_char)`).
    *   This `digit` is then raised to the power of `num_digits` (the total count of digits in the original number) using the exponentiation operator (`**`).
    *   The result of this exponentiation is added to `sum_of_powers`.

3.  **Comparison and Return Value:**
    After the loop completes, `sum_of_powers` holds the sum of each digit raised to the power of the number of digits. The function then compares this `sum_of_powers` with the original `number`.
    *   If `sum_of_powers` is equal to `number`, it means the number fits the definition of an Armstrong number, and the function returns `True`.
    *   Otherwise, if they are not equal, the function returns `False`.

In essence, an Armstrong number is defined by this process: take a number, count its digits, then sum each digit raised to the power of that count. If the result is the original number, it's an Armstrong number.

**Example Usage:**

The code block also includes several `print` statements that demonstrate how to use the `is_armstrong` function:
*   `print(f"Is 153 an Armstrong number? {is_armstrong(153)}")` checks `153`, which is expected to be `True`.
*   `print(f"Is 9 an Armstrong number? {is_armstrong(9)}")` checks `9` (a single-digit number is an Armstrong number if it's equal to itself raised to the power of 1), expected `True`.
*   `print(f"Is 371 an Armstrong number? {is_armstrong(371)}")` checks `371`, expected `True`.
*   `print(f"Is 123 an Armstrong number? {is_armstrong(123)}")` checks `123`, expected `False`.
*   `print(f"Is 1634 an Armstrong number? {is_armstrong(1634)}")` checks `1634`, expected `True`.

These examples showcase the function's behavior for both Armstrong and non-Armstrong numbers of different digit counts.

## Optimize Armstrong Number Program

### Subtask:
Refactor and optimize the previously generated Armstrong number program for better efficiency.


**Reasoning**:
The subtask requires refactoring and optimizing the Armstrong number program. I will define a new function `is_armstrong_optimized` that calculates the number of digits and the sum of powers using mathematical operations (modulo and integer division) instead of string conversion, which is generally more efficient for numerical operations. This aligns with the instructions for optimization.



In [5]:
def is_armstrong_optimized(number):
    original_number = number
    temp_number = number
    num_digits = 0

    # Calculate the number of digits
    if number == 0: # Handle the case for 0
        num_digits = 1
    else:
        while temp_number > 0:
            temp_number //= 10
            num_digits += 1

    sum_of_powers = 0
    temp_number = original_number # Reset temp_number to iterate through digits

    # Calculate the sum of powers of digits
    while temp_number > 0:
        digit = temp_number % 10
        sum_of_powers += digit ** num_digits
        temp_number //= 10

    return sum_of_powers == original_number

# Example usage:
print("Optimized function results:")
print(f"Is 153 an Armstrong number? {is_armstrong_optimized(153)}")  # Expected: True
print(f"Is 9 an Armstrong number? {is_armstrong_optimized(9)}")    # Expected: True
print(f"Is 371 an Armstrong number? {is_armstrong_optimized(371)}")  # Expected: True
print(f"Is 123 an Armstrong number? {is_armstrong_optimized(123)}")  # Expected: False
print(f"Is 1634 an Armstrong number? {is_armstrong_optimized(1634)}") # Expected: True
print(f"Is 0 an Armstrong number? {is_armstrong_optimized(0)}")     # Expected: True (0^1 = 0)
print(f"Is 1 an Armstrong number? {is_armstrong_optimized(1)}")     # Expected: True (1^1 = 1)

Optimized function results:
Is 153 an Armstrong number? True
Is 9 an Armstrong number? True
Is 371 an Armstrong number? True
Is 123 an Armstrong number? False
Is 1634 an Armstrong number? True
Is 0 an Armstrong number? True
Is 1 an Armstrong number? True


## Summarize Improvements

### Subtask:
Clearly articulate the changes made during the optimization step and explain why these changes lead to an improved program.


### Summary of Improvements in the Optimized Armstrong Number Program

During the optimization step, the `is_armstrong` function was refactored into `is_armstrong_optimized`. The primary change and source of improvement lies in how the digits of the number are processed and the number of digits is determined.

**Original `is_armstrong` Function:**
*   **Approach:** Converted the input `number` to a string (`str(number)`). This allowed for easy counting of digits (`len(num_str)`) and iteration through individual digits (`for digit_char in num_str`).
*   **Method for Digit Extraction:** String iteration.
*   **Method for Digit Count:** `len()` of the string.

**Optimized `is_armstrong_optimized` Function:**
*   **Approach:** Relies entirely on mathematical operations (integer division and modulo) to count digits and extract them.
*   **Method for Digit Extraction:** Uses the modulo operator (`% 10`) to get the last digit and integer division (`// 10`) to remove the last digit, repeating until the number becomes zero.
*   **Method for Digit Count:** A `while` loop with integer division (`// 10`) increments a counter until the number is reduced to zero.

**Why these changes lead to an improved program (Optimization Benefits):**

1.  **Avoidance of Type Conversion Overhead:** The most significant optimization comes from avoiding the conversion of the integer `number` to a string and back to an integer for each digit. Type conversions, especially between numerical types and strings, can be computationally expensive. Python needs to allocate memory for the new string object, populate it with character data, and then for each character, convert it back to an integer. The optimized version performs direct arithmetic operations, which are natively fast at the processor level.

2.  **Efficiency of Arithmetic Operations:** Integer division (`//`) and the modulo operator (`%`) are fundamental arithmetic operations that processors handle very efficiently. They are generally much faster than string manipulation functions (like `len()` and string iteration) when dealing with numerical data, especially in a loop.

3.  **Memory Efficiency:** While not a major concern for typical integer sizes, avoiding string conversions also implicitly reduces temporary memory allocations. Each string conversion creates a new string object in memory. For very large numbers or repeated calls, this could lead to less optimal memory usage.

4.  **Scalability:** For extremely large numbers (though Python's arbitrary-precision integers might mitigate some string-related scaling issues for very large numbers), arithmetic manipulation tends to scale more predictably and efficiently than string-based approaches.

5.  **Readability (Maintained):** Despite the technical change, the `is_armstrong_optimized` function maintains a high level of readability. The use of `while` loops with modulo and integer division is a common and understandable pattern for digit manipulation in numerical algorithms.

In summary, by switching from string-based processing to purely mathematical operations, the `is_armstrong_optimized` function achieves better efficiency by reducing type conversion overhead and leveraging faster, native arithmetic computations, while retaining its clarity.

## Final Task

### Subtask:
Conclude the task by presenting both versions of the code and the summary of improvements.


## Summary:

### Data Analysis Key Findings

*   **Initial Implementation Success**: The initial `is_armstrong` function was successfully developed, correctly identifying Armstrong numbers (e.g., 153, 9, 371, 1634) and non-Armstrong numbers (e.g., 123) by converting the input number to a string to count digits and sum powers.
*   **Logic Explanation**: A detailed explanation of the initial function's logic was provided, outlining how it converts numbers to strings, iterates through digits, calculates the sum of digits raised to the power of the total digit count, and compares this sum to the original number.
*   **Optimized Implementation**: An `is_armstrong_optimized` function was developed that avoids string conversion. It uses mathematical operations (integer division `//` and modulo `\%`) to count digits and extract them, leading to improved efficiency.
*   **Optimized Function Correctness**: The optimized function also correctly identified Armstrong numbers, including edge cases like 0 and 1, confirming its accuracy.
*   **Performance Improvement Source**: The primary improvement in the optimized version stems from replacing computationally expensive string conversions and manipulations with native, faster arithmetic operations. This reduces type conversion overhead, enhances the efficiency of digit processing, and potentially improves memory usage and scalability.

### Insights or Next Steps

*   **Prioritize Arithmetic for Numerical Tasks**: When dealing with numerical data in Python, especially for digit manipulation, prioritize arithmetic operations (e.g., modulo, integer division) over string conversions for better performance and efficiency, as type conversions introduce overhead.
*   **Benchmark Performance**: For future optimizations, consider benchmarking both versions of the function with a range of input sizes (e.g., small, medium, and very large numbers) to quantify the performance gains achieved by the optimization.
